# GitHub Sponsors (Enable at https://github.com/sponsors)
github: [nexoscreator, nexoslabs] # , nexoscrating

# Other funding platforms
# open_collective: nexoscreator
# buy_me_a_coffee: nexoscreator
custom: [https://www.paypal.me/nexoscreator, 'https://www.nexoscreation.tech/donate']
